<!DOCTYPE html>
<html lang="fr">
    <?php
        include "header.phtml";
    ?>
    <main>
        <body class="cabinet">
            <h1>situer le cabinet</h1>
            <hr>
            <div class="adresse" >
                <a>
                    <h4> Adresse </h4>
                    <p>2 bis Rue des Frênes</p>
                    <p>85560 Le Bernard</p><hr>
                </a>
            </div>
            <div>
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d124403.76003568026!2d-1.5559047348517883!3d46.44999602419549!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x841a2420c05730cf!2sLara+Kappeler+Ost%C3%A9opathe!5e0!3m2!1sfr!2sfr!4v1538510890774" width="100%" height="500" frameborder="10px" style="border:10px" allowfullscreen></iframe>
            </div><hr>
            <div class="horaire">
                <h4>Les horaires d'ouverture</h4>
                <ul>
                    <li>lundi	9h – 19h</li>
                    <li>mardi	9h – 19h</li>
                    <li>mercredi   9h – 19h</li>
                    <li>jeudi	9h – 19h</li>
                    <li>vendredi   9h – 19h</li>
                    <li>samedi	9h – 13h</li>
                </ul><hr>
            </div>
            <div class="pratique">
                <h4> Infos pratiques :</h4>
                <p> Le cabinet est equipé pour les personnes Handicapées </p>
                <p> Un grand parking est a disposition juste devant, avec des places reservées pour les personnes a mobilité réudite</p>
            </div><hr>
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img class="d-block w-100" src="img/cabinet1.jpg" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" src="img/cabinet2.jpg" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" src="img/cabinet3.jpg" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            <hr>
        </body>
    </main>
    <?php
        include "footer.html";
    ?>
</html>