<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="css/normalize.css">
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <link href="https://fonts.googleapis.com/css?family=CormorantUpright" rel="stylesheet">
    <meta charset="utf-8">
    <?php
        include "script-file.phtml";
    ?>
    <title> Lara Kappeler Osteopathie Vendee Le Bernard 85 </title>
    <header>
        <nav class="headernav">
            <a href="index.phtml" id="logo1" id="logo2" ><h2>Lara Kappeler Ostéopathe D.O</h2></a>
            <ul class="nav nav-pills " id="nav_bar">
                <li class="nav-item">
                    <a class="nav-link " href="index.phtml">Accueil</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link bg-transparent " data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">L'ostéopathie </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="l'osteopathie.phtml">Qu'est ce que l'ostéopathie ?</a>
                            <a class="dropdown-item" href="qui.phtml">Pour qui ?</a>
                            <a class="dropdown-item" href="quand.phtml">Quand ?</a>
                        </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="praticienne.phtml">Présentation</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link bg-transparent " data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Infos pratiques</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="consultation.html">La Consultation</a>
                            <a class="dropdown-item" href="honoraires.phtml">Les Honoraires</a>
                            <a class="dropdown-item" href="cabinet.phtml">Le cabinet</a>
                            <a class="dropdown-item" href="newslater.php">nouveauté</a>
                        </div>
                </li>
            </ul>
        </nav>
        <li class="trait"></li>
    </header>
</head>