<!DOCTYPE html>
<html lang="fr">
<?php
		include "header.phtml";
	?>
<body>
	<section>
		<div class="bloc-honoraire">
			<h3>Les Honoraires appliqués </h3>
			<table class="honoraires">
				<tr>
					<th>type de consultation</th>
					<th>prix</th>
				</tr>
				<tr>
					<td>Premiere consultation</td>
					<td>50 €</td>
				</tr>
				<tr>
					<td>Consultation de suivie</td>
					<td>50 €</td>
				</tr>
				<tr>
					<td>Consultation pour sportif/(ve)</td>
					<td>50 €</td>
				</tr>
				<tr>
					<td>Consultation enfant</td>
					<td>50 €</td>
				</tr>
				<tr>
					<td>Consultation femme enceinte</td>
					<td>50 €</td>
				</tr>
				<tr>
					<td>Consultation pour nourisson</td>
					<td>50 €</td>
				</tr>
				<tr>
					<td>Consultation Maman-nourisson</td>
					<td>85 €</td>
				</tr>
			</table>
		</div>
	</section>
	<section>
		<div class="paiement">
			<h4>Moyens de paiement</h4>
			<ul>
				<li>- Especes</li>
				<li>- Cheque bancaire</li>
				<li>- Carte bancaire</li>
			</ul>
		</div>
	</section><hr>
</body>
<?php
		include "footer.html";
	?>
</html>