<!DOCTYPE html>
<?php 	
	session_start();
?>
<html lang="fr">
	<?php
		include "header.phtml";
	?>
	<main>
		<div class="img">
			<section >
				<article class="centrale">
					<h3>Lara Kappeler</h3>
					<p>Ostéopathe</p>
					<a href="https://www.pagesjaunes.fr/pros/55639220" id="lien_rdv">Prendre rendez-vous</a>
				</article>
			</section>
		</div>
	</main>
	<div class="trois">
		<section id="case1">
			<h4>Cabinet d'ostéopathie</h4>
			<p>2 bis Rue des Frênes</p>
			<p>85560 Le Bernard</p>
		</section>
		<section id="case2">
			<h4><a "tel:+33251900906">02 51 90 09 06</a></h4>
			<a href="mailto:lk.osteopathe@gmail.com" class="mail">lk.osteopathe@gmail.com</a>
		</section>
		<section id="case3">
			<h4>Horaires :</h4>
			<ul>
				<li>lundi	9h – 19h</li>
				<li>mardi	9h – 19h</li>
				<li>mercredi   9h – 19h</li>
				<li>jeudi	9h – 19h</li>
				<li>vendredi   9h – 19h</li>
				<li>samedi	9h – 13h</li>
			</ul>
		</section>
	</div>
		<section>
			<?php if (isset($_SESSION['pseudo'])) {
				echo  $_SESSION['pseudo']."bonjour ";
			} ?>
			<section class="footer">
				<?php if(isset($_SESSION) && isset($_SESSION['pseudo']) ) : ?>
					<form method="post" action="deconnect.php?action=deconnexion" name="deconnexion">
						<button>deconnexion</button>
					</form>
					<a href="laraPost.php"><button>page de controle</button></a>
				<?php endif; ?>
			</section>
		</section>
	<small id="footer" >
		<a href="mentionslegales.phtml"> mentions legales  <p>tout droit réserver</p></a>
		<?php if (isset($_SESSION)) : ?>
			<a href="log1.php" class="log1">admin</a>
		<?php endif; ?>
		<p>copyright C 2018</p>
		</small>
</html>