<!DOCTYPE html>
<html lang="fr">
	<?php
		include "header.phtml";
	?>
	<body>
		<main class="newslater">
			<?php if(isset($_SESSION) && isset($_SESSION['pseudo'])):
			foreach ($post as $key => $value) : ?>
				<article class="post">
					<p><?= $value['titre']; ?></p>
					<p><?= $value['content']; ?></p>
					<p><i class="far fa-trash-alt"></i>
						<a href="delete.php?id=<?= $value["id"]; ?>">Delete</a>
					</p>
				</article>
			<?php endforeach?>
			<?php endif ?>
		</main>
	<div>
		<section>
			<?php if (isset($_SESSION['pseudo'])) {
				echo "bonjour ". $_SESSION['pseudo'];
			} ?>
			<?php if(isset($_SESSION) && isset($_SESSION['pseudo']) ) : ?>
				<a href="news.php" class="ajouter"><button>crée un article</button></a>
				<form method="post" action="log1.php?action=deconnexion" name="deconnexion">
					<button>deconnexion</button>
				</form>
			<?php endif; ?>
		</section>
	</div>
	</body>
	<?php
		include "footer.html";
	?>
</html>