<!DOCTYPE html>
<html lang="fr">
	 <?php
	   include "header.phtml";
	 ?>
	<main>
		<div class="img">
			<section >
				<article class="centrale">
					<?php if(isset($_SESSION)) : ?>
							<p> "vous etes deja connecter !!"</p>;
						<?php endif ?>
						<?php if (!isset($_SESSION)) : ?>
							<p>connexion</p>
							<form method="post" action="log1.php" class="formlog">
								<p>
									<input type="text" name="pseudo" id="pseudo" placeholder="login" />
									<br />
									<input type="password" name="password" id="password" placeholder="password" />
									<br />
									<button type="submit">connecter</button>
								</p>
							</form>
					<?php endif ?>
				</article>
			</section>
		</div>
	</main>
	<div>
		<section>
			<button><a href="index.phtml">acceuil</a></button>
			<?php if(isset($_SESSION) && isset($_SESSION['pseudo']) ) : ?>
				<form method="post" action="deconnect.php?action=deconnexion" name="deconnexion">
					<button>deconnexion</button>
				</form>
				<a href="laraPost.php"><button>page de controle</button></a>
			<?php endif; ?>
		</section>
	</div>
	 <?php
	 	include "footer.html";
	 ?>
</html>