<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>mentions-legales</title>
</head>
<header>
    <?php
	   include "header.phtml";
	 ?>
</header>
<body>
    <div class="mentions">
        <p>  Toute utilisation et reproduction est interdite sans l'autorisation de l'auteur et du mandataire. Tous droits réservés.</p>
        <hr>
        <img src="img/copyright.jpg">
        <hr>
        <p>site crée et propulsé par Lionel Cochereau</p>
        <hr>
    </div>
</body>
</html>