<!DOCTYPE html>
<html lang="fr">
	<?php
		include "header.phtml";
	?>
	<main>
		<p id="news">nouvel article</p>
		<form method="post" action="news.php" class="formlog">
			<p>
				<input type="text" name="titre" id="titre" placeholder="titre" />
				<br />
				<textarea class="tinimce" placeholder="texte" name="text" id="text" rows="15"></textarea>
				<br />
				<button type="submit">poster</button>
			</p>
		</form>
	</main>
	<div>
		<section>
			<a href="log1.php" class="log1"><button>admin</button></a>
				<?php if(isset($_SESSION) && isset($_SESSION['pseudo']) ) : ?>

				<form method="post" action="log1.php?action=deconnexion" name="deconnexion">
					<button>deconnexion</button>
				</form>
				<a href="laraPost.php"><button>page de controle</button></a>
			<?php endif; ?>
		</section>
	</div>
	<?php
		include "footer.html";
	?>
</html>